src/Entity/Skill.php
<?php

namespace App\Entity;

use App\Repository\SkillRepository;
use App\Entity\Project;
use App\Entity\Picture;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=SkillRepository::class)
 * @UniqueEntity(
 *     fields={"name"},
 *     errorPath="name",
 *     message="Ce nom existe déjà."
 * )
 */
class Skill implements \JsonSerializable
{

    const LEVEL = [
        0 => "Null",
        1 => "Débutant",
        2 => "Intermédiaire",
        3 => "Confirmé",
        4 => "Expert"
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $name;

    /**
     * @ORM\OneToOne(targetEntity=picture::class, cascade={"persist", "remove"})
     */
    private $icon;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $level;

    public function __construct(){
        $this->level = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        
        return $this;
    }

    public function getIcon(): ?picture
    {
        return $this->icon;
    }

    public function setIcon(?picture $icon): self
    {
        $this->icon = $icon;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function jsonSerialize(): string
    {
        // This entity implements JsonSerializable (http://php.net/manual/en/class.jsonserializable.php)
        // so this method is used to customize its JSON representation when json_encode()
        // is called, for example in tags|json_encode (templates/form/fields.html.twig)

        return $this->name;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getFormatedLevel(): string
    {
        return self::LEVEL[$this->level];
    }

    
}

src/Controller/AproposController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Repository\SkillRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class AproposController extends AbstractController
{

    private $repository;

    public function __construct(SkillRepository $repository){

        $this->repository = $repository;
    }

    /**
     * @Route("/apropos", name="apropos")
     */
    public function index()
    {

        $skills = $this->repository->findAllWithPictures();

        return $this->render('apropos/index.html.twig', [
            'skills' => $skills, 
        ]);
    }

    /**
     * @Route("/cv", name="cv")
     */
    public function show()
    {

        $skills =$this->repository->findAllWithPictures();

        return $this->render('apropos/show.html.twig', [
            'skills' => $skills, 
        ]);
    }
}

templates/apropos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Qui suis-je?{% endblock %}

{% block stylesheets %}

<link rel="stylesheet" type="text/css" href="{{ asset('build/apropos.css') }}">

{% endblock %}

{% block body %}

<div class="apropos-container">
	
	<div class="cv">

		<div class="presentation">
			<h3>Christopher Bonhomme </h3>
			<div>
				<img class="img-pres" src="{{ asset('/img/photo-black-white.jpg') }}" alt="logo" width="150px">
			</div>
			<div class="profile-link">
				<div>
					<a href="https://www.linkedin.com/in/christopher-bonhomme-995957213/"><img class="img-no" src="{{ asset('/img/linkedin.webp') }}" alt="logo" width="50px"></a>
				</div>
				<div>
					<a href="https://gitlab.com/chris07"><img class="img-no" src="{{ asset('/img/gitlab.webp') }}" alt="logo" width="50px"></a>
				</div>
			</div>
			<p>
				Développeur Web Junior
			</p>
			<p>
				Recherche alternance en contrat de professionnalisation à partir de septembre 2021.
			</p>
		</div>
		<div class="contenu">
			<div class="col-skills-interests">
				<div class="interests">
					<h5>contacts</h5>
					<hr>
					<div>
						<div class="underline">Adresse e-mail:</div>
						<a href="mailto:christopher.bonhomme@gmail.com">christopher.bonhomme@gmail.com</a>
					</div>
					<div>
						<div class="underline">Téléphone:</div>
						<div>06 08 04 85 46</div>
					</div>
					<div>
						<div class="underline">Mon Portfolio:</div>
						<a href="{{ path('accueil') }}">https://lockmark.fr/</a>
					</div>
				</div>
				<br>
				<div class="skills">
					<h5>Compétences</h5>
					<hr>

				{% for skill in skills %}
						
					<div class="skill">

						{% if skill.icon %}

							<div>
							  <img src="{{ asset('/uploads/' ~ skill.icon.name) }}" loading="lazy" alt="{{ skill.name }} " width="50px">
							</div>

						{% else %}

							<div>
							  {{ skill.name }}
							</div>

						{% endif %}

							<div class="bar">		
								<div class="anim">
									{{ skill.formatedLevel }}
									<input class="v" type="hidden" name="level" value="{{ skill.level }}">
								</div>
							</div>
					</div>

				{% endfor %}

				</div>
				<br>
				<div class="interests">
					<h5>Intérets</h5>
					<hr>
					<div class="musique">
						<div>Musique</div>
						<div class="img-rond"><img src="{{ asset('/img/metal60.webp') }}" loading="lazy" alt="metal" width="60px"></div>
					</div>
					<br/>
					<div class="nature">
						<div>Nature</div>
						<div class="img-rond"><img src="{{ asset('/img/arbre60.webp') }}" loading="lazy" alt="nature" width="60px"></div>
					</div>
					<br/>
					<div class="sport">
						<div>Sport</div>
						<div class="img-rond"><img src="{{ asset('/img/bike60.webp') }}" loading="lazy" alt="bike" width="60px"></div>
					</div>
					<br/>
					<div class="informatique">
						<div>Informatique</div>
						<div class="img-rond"><img src="{{ asset('/img/info60.webp') }}" loading="lazy" alt="informatique" width="60px"></div>
					</div>
				</div>
			</div>
			<div class="col-formation-exp">
				<div class="exp">
					<h5>Expériences professionnelles</h5>
					<hr>
					<br/>
					<div class="exp-pro">
						<div class="annee">
							<div>2020</div>
							<div>|</div>
							<div>|</div>
							<div>|</div>
							<div>2019</div>
						</div>
						<div class="poste">
							<div><br/></div>
							<div class="intit">Administrateur ERP</div>
							<div>Mistral Semences Remington Seeds</div>
							<div>26700 Pierrelatte</div>
						</div>
					</div>
					<br/>
					<hr>
					<br/>
					<div class="exp-pro">
						<div class="annee">
							<div>2018</div>
							<div>|</div>
							<div>|</div>
							<div>|</div>
							<div>2012</div>
						</div>
						<div class="poste">
							<div><br/></div>
							<div class="intit">Technicien Sportif Saisonnier</div>
							<div>Intersport</div>
							<div>73440 Les Menuires + Autres Stations</div>
						</div>
					</div>
					<br/>
					<hr>
					<br/>
					<div class="exp-pro">
						<div class="annee">
							<div>2012</div>
							<div>|</div>
							<div>|</div>
							<div>|</div>
							<div>2010</div>
						</div>
						<div class="poste">
							<div><br/></div>
							<div class="intit">Manager</div>
							<div>Mac Donalds Autoroutes</div>
							<div>26780 Allan</div>
						</div>
					</div>
					<br/>
				</div>
				<br/>
				<div class="exp">
					<h5>Projets Personnels</h5>
					<hr>
					<div>
						<div class="intit">Application de partage de données mycologiques (projet en cours)</div>
						<div>Une appli web et mobile couplées à une web API REST qui a pour but le partages de données scientifiques.</div>
						<div><a href="#">https://gitlab.com/chris07/champi_app</a></div>
					</div>
					<hr>
					<div>
						<div class="intit">Mon Blog</div>
						<div>Un blog Fait avec Vue.js, VueX, VueRouter et API Platform. Interfaces d'administration et de modération incluses.</div>
						<div><a href="#">https://blogfront.lockmark.fr/home</a></div>
					</div>
					<hr>
					<div>
						<div class="intit">E-commerce de la savonnerie artisanale Poplume</div>
						<div>Un site e-commerce fait avec Wordpress pour une savonnerie artisanale locale.</div>
						<div><a href="#">https://poplume.com/</a></div>
					</div>
				</div>
				<br/>
				<div class="formation">
					<h5>Formations</h5>
					<hr>
					<br/>
					<div class="learn">
						<div>2018</div>
						<div>Formation Développeur Logiciel Niveau 3</div>
						<div>Le Cheylard 07 160</div>
					</div>
					<br/>
					<div class="learn">
						<div>2012</div>
						<div>Formation Technicien Cycles Niveau 4</div>
						<div>Grenoble 38 000</div>
					</div>
					<br/>
					<div class="learn">
						<div>2010</div>
						<div>Formation Management Niveau 3</div>
						<div>Guillancourt 78 280</div>
					</div>
					<br/>
					<div class="learn">
						<div>2008</div>
						<div>Formation Technicien Skis Niveau 4</div>
						<div>Annecy 74 000</div>
					</div>
					<br/>
					<div class="learn">
						<div>2005</div>
						<div>BAC Technologique option Commerce</div>
						<div>Montélimar 26 200</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="{{ asset('build/apropos.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/anime-cv.js') }}"></script>
{% endblock %}

templates/apropos/show.html.twig
{% extends 'basecv.html.twig' %}

{% block title %}CV{% endblock %}

{% block stylesheets %}

<link rel="stylesheet" type="text/css" href="{{ asset('build/cv.css') }}">

{% endblock %}

{% block body %}

<div class="apropos-container">
	
	<div class="cv">

		<div class="presentation">
			<h3>Christopher Bonhomme </h3>
			<div>
				<img class="img-pres" src="{{ asset('/img/photo-black-white.jpg') }}" alt="logo" width="150px">
			</div>
			<div class="profile-link">
				<div>
					<a href="https://www.linkedin.com/in/christopher-bonhomme-995957213/"><img class="img-no" src="{{ asset('/img/linkedin.webp') }}" alt="logo" width="50px"></a>
				</div>
				<div>
					<a href="https://gitlab.com/chris07"><img class="img-no" src="{{ asset('/img/gitlab.webp') }}" alt="logo" width="50px"></a>
				</div>
			</div>
			<p>
				34 ans
			</p>
			<p>
				Développeur Web Junior
			</p>
			<p>
				Recherche alternance en contrat de professionnalisation à partir de septembre 2021.
			</p>
		</div>
		<div class="contenu">
			<div class="col-skills-interests">
				<div class="interests">
					<h5>contacts</h5>
					<hr>
					<div>
						<div class="underline">Adresse e-mail:</div>
						<a href="mailto:christopher.bonhomme@gmail.com">christopher.bonhomme@gmail.com</a>
					</div>
					<div>
						<div class="underline">Téléphone:</div>
						<div>06 08 04 85 46</div>
					</div>
					<div>
						<div class="underline">Mon Portfolio:</div>
						<a href="{{ path('accueil') }}">https://lockmark.fr/</a>
					</div>
				</div>
				<br>
				<div class="skills">
					<h5>Compétences</h5>
					<hr>

				{% for skill in skills %}
						
					<div class="skill">

						{% if skill.icon %}

							<div>
							  <img src="{{ asset('/uploads/' ~ skill.icon.name) }}" loading="lazy" alt="{{ skill.name }} " width="50px">
							</div>

						{% else %}

							<div>
							  {{ skill.name }}
							</div>

						{% endif %}

							<div class="bar">		
								<div class="anim">
									{{ skill.formatedLevel }}
									<input class="v" type="hidden" name="level" value="{{ skill.level }}">
								</div>
							</div>
					</div>

				{% endfor %}

				</div>
				<br>
				<div class="interests">
					<h5>Intérets</h5>
					<hr>
					<div class="musique">
						<div>Musique</div>
						<div class="img-rond"><img src="{{ asset('/img/metal60.webp') }}" loading="lazy" alt="metal" width="60px"></div>
					</div>
					<br/>
					<div class="nature">
						<div>Nature</div>
						<div class="img-rond"><img src="{{ asset('/img/arbre60.webp') }}" loading="lazy" alt="nature" width="60px"></div>
					</div>
					<br/>
					<div class="sport">
						<div>Sport</div>
						<div class="img-rond"><img src="{{ asset('/img/bike60.webp') }}" loading="lazy" alt="bike" width="60px"></div>
					</div>
					<br/>
					<div class="informatique">
						<div>Informatique</div>
						<div class="img-rond"><img src="{{ asset('/img/info60.webp') }}" loading="lazy" alt="informatique" width="60px"></div>
					</div>
				</div>
			</div>
			<div class="col-formation-exp">
				<div class="exp">
					<h5>Expériences professionnelles</h5>
					<hr>
					<br/>
					<div class="exp-pro">
						<div class="annee">
							<div>2020</div>
							<div>|</div>
							<div>|</div>
							<div>|</div>
							<div>2019</div>
						</div>
						<div class="poste">
							<div><br/></div>
							<div class="intit">Administrateur ERP</div>
							<div>Mistral Semences Remington Seeds</div>
							<div>26700 Pierrelatte</div>
						</div>
					</div>
					<br/>
					<hr>
					<br/>
					<div class="exp-pro">
						<div class="annee">
							<div>2018</div>
							<div>|</div>
							<div>|</div>
							<div>|</div>
							<div>2012</div>
						</div>
						<div class="poste">
							<div><br/></div>
							<div class="intit">Technicien Sportif Saisonnier</div>
							<div>Intersport</div>
							<div>73440 Les Menuires + Autres Stations</div>
						</div>
					</div>
					<br/>
					<hr>
					<br/>
					<div class="exp-pro">
						<div class="annee">
							<div>2012</div>
							<div>|</div>
							<div>|</div>
							<div>|</div>
							<div>2010</div>
						</div>
						<div class="poste">
							<div><br/></div>
							<div class="intit">Manager</div>
							<div>Mac Donalds Autoroutes</div>
							<div>26780 Allan</div>
						</div>
					</div>
					<br/>
				</div>
				<br/>
				<div class="exp">
					<h5>Projets Personnels</h5>
					<hr>
					<div>
						<div class="intit">Application de partage de données mycologiques (projet en cours)</div>
						<div>Une appli web et mobile couplées à une web API REST qui a pour but le partages de données scientifiques.</div>
						<div><a href="#">https://gitlab.com/chris07/champi_app</a></div>
					</div>
					<hr>
					<div>
						<div class="intit">Mon Blog</div>
						<div>Un blog Fait avec Vue.js, VueX, VueRouter et API Platform. Interfaces d'administration et de modération incluses.</div>
						<div><a href="#">https://blogfront.lockmark.fr/home</a></div>
					</div>
					<hr>
					<div>
						<div class="intit">E-commerce de la savonnerie artisanale Poplume</div>
						<div>Un site e-commerce fait avec Wordpress pour une savonnerie artisanale locale.</div>
						<div><a href="#">https://poplume.com/</a></div>
					</div>
				</div>
				<br/>
				<div class="formation">
					<h5>Formations</h5>
					<hr>
					<br/>
					<div class="learn">
						<div>2018</div>
						<div>Formation Développeur Logiciel Niveau 3</div>
						<div>Le Cheylard 07 160</div>
					</div>
					<br/>
					<div class="learn">
						<div>2012</div>
						<div>Formation Technicien Cycles Niveau 4</div>
						<div>Grenoble 38 000</div>
					</div>
					<br/>
					<div class="learn">
						<div>2010</div>
						<div>Formation Management Niveau 3</div>
						<div>Guillancourt 78 280</div>
					</div>
					<br/>
					<div class="learn">
						<div>2008</div>
						<div>Formation Technicien Skis Niveau 4</div>
						<div>Annecy 74 000</div>
					</div>
					<br/>
					<div class="learn">
						<div>2005</div>
						<div>BAC Technologique option Commerce</div>
						<div>Montélimar 26 200</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="{{ asset('build/cv.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/anime-cv.js') }}"></script>
{% endblock %}